### ISSUE TITLE
Min JDK Upgrade from JDK 8 to 17

### ISSUE THREAD

**Issue by sathishk** [unloggedio/unlogged-sdk#2]
We have [dependencies](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.javadoc/com/sun/tools/javadoc/package-summary.html) with deprecated packages **com.sun.tools**.  This is due to our intent to support JDK 8.

Considering that our actual target is Spring Boot. And **Spring Boot Min version is JDK 17**, Most of  the enterprises started to upgrade now. 

If This SDK is updated we can gain natural performance from JDK 17 also cleanup the deprecated code

**Comment by bharathkalyans** [comment]
* True, many libraries arent supporting the old Spring Boot.
