### ISSUE TITLE
Functional Issue of "Save Replay" button

### ISSUE THREAD

**Issue by kishore-khumar** [unloggedio/unlogged-sdk#25]
### Describe the bug

The "save replay" button in the service class of certain spring boot projects is malfunctioning, preventing the visibility of assertion and mock data operations.

Kindly refer the below attached pdf.

[issues screenshots.pdf](https://github.com/unloggedio/unlogged-sdk/files/13859332/issues.screenshots.pdf)

### Reproduction steps

1. Install Unlogged plugin in Intellij IDEA and add unlogged dependency based on your Java version.
2.Add Unlogged annotation above your main method of your project.
3.Run "mvn clean" command and start your application.
4.Click 'Save Replay' button of unlogged tab from your service class of spring boot project
5. I am unable to locate the assertion and mock data tab, indicating that the button was unable to carry out its intended function.

### Expected behavior

When invoking the "save replay" button within the service class of specific Spring Boot projects, it is imperative that the functionality operates seamlessly without any malfunctions. This ensures the smooth execution of tasks and prevents any disruptions that might hinder the visibility of assertion and mock data operations. The proper functioning of this button is crucial to maintain the integrity of the application, allowing for the accurate recording and storage of replay data while facilitating a clear and unobstructed view of assertion and mock data manipulations.

**Comment by kartikeytewari-ul** [comment]
Thanks for raising the bug! We are actively working on it and will fix this.

**Comment by artpar** [comment]
This is resolved.
