### ISSUE TITLE
refactor: Refactoring of the code base

### ISSUE THREAD

**Issue by bharathkalyans** [unloggedio/unlogged-sdk#5]
* Codebase contains a lot of warnings and redundant code.
Eg.The below code can have a private constructor, so an object can't be created.
```java
public class Constants {
    public static final String AGENT_VERSION = "1.0.1";
}
```

**Comment by bharathkalyans** [comment]
@artpar I would love to work on this!!
Can you assign this to me?

**Comment by artpar** [comment]
@bharathkalyans Thanks for the PR. 

Changes which rearrange the keywords and reformat the code are something which I don't want to accept at this point.

This leaves the 3 changes, 

- `Contants.java` private constructor
- fixing of the comment in `Unlogged.java` 
- `ClassTypeUtil.java` private constructor

They look fine and I can merge them if you can remove the formatting changes.

**Comment by bharathkalyans** [comment]
@artpar New PR fix the requirements? Would you like me to fix anything else?

**Comment by artpar** [comment]
Merged. Thanks @bharathkalyans
