### ISSUE TITLE
Class does not have dual methods with frequency logging build

### ISSUE THREAD

**Issue by kartikeytewari-ul** [unloggedio/unlogged-sdk#65]
### Describe the bug

Project: unlogged-spring-gradle-demo
Class: ReferralUtils

When building the project with frequency logging build of SDK the class does not have dual methods. Instead the decompiled class only have a single probed method. This causes the methods in class to be always probed.

### Reproduction steps

1. Run the process with frequency_logging SDK build and latest plugin with some set counter.
2. Direct Invoke a method in ReferralUtils many times
3. It will show up all the time in live window.

### Expected behavior

The method should be seen only a few times based on the set counter of the process.

### Additional context

This can be also verified by looking at the decompiled class.

**Comment by kartikeytewari-ul** [comment]
## Root Cause Analysis

- The flow for bytecode injection for static and non-static methods is different. There is a bug in how bytecode injection happens for static methods. 
- The filter blocked static methods from getting modified and hence this bug never arised. The methods were always getting probed.
- The approach for method injection is to first load data in stack like object instance (this keyword) and arguments with which the method is to be invoked.  Then call the `mv.visitMethodInsn()` method. For static methods the stack trace was supposed to be prepared with arguments and then the call to `mv.visitMethodInsn()` needed to happen. 
- Instead the stack never got prepared with arguments for static methods. 
- As a result when the filter was removed static methods without arguments (generally methods like ReferralUtils#generateReferralCode of usmd) got probed correctly. While static methods with arguments (generally lambda methods throughout the project) got injected incorrectly.
- This bug has nothing to do with regular/lambda methods. When filter is removed any method that is static and has some arguments will be injected incorrectly. It just so happens that those methods were lambda in usmd project.

**Comment by kartikeytewari-ul** [comment]
This is fixed with SDK v0.6.101 [video demo](https://drive.google.com/file/d/15agGZNVEKH0Dv11gVi_YqjKCSt-n4C7M/view?usp=drive_link)

**Comment by TheAmg** [comment]
Static methods will now generate candidates correctly based on counter specified.
(With the exception of #83).

Closing the issue.
